# Config file for automatic testing at travis-ci.org

language: python

python:
{{travis.pyversions,
  - "2.7"
}}

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install -r requirements.txt
 {{coveralls rm, - pip install coveralls}}

# command to run tests, e.g. python setup.py test
script: nosetests

{{coveralls rm,
after_success:
  coveralls
}}