# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
{%- for pyver in pysetup.intended_versions %}
  - "{{ pyver[0] }}.{{ pyver[1] }}"
{%- endfor %}
# #}

# {# pkglts, travis.addons
addons:
  apt:
    packages:
# #}

# {# pkglts, travis.install
install:
 - pip install -r requirements.txt
 - pip install -r dvlpt_requirements.txt
{%- if 'coveralls' is available %}
 - pip install coveralls
{%- endif %}
# #}

# {# pkglts, travis.script
script:
 - nosetests
# #}

# {# pkglts, travis.after
after_success:
{%- if 'coveralls' is available %}
  - coveralls
{%- endif %}
# #}
